// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#include <lvgl.h>
#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

    /**
     * ################################################
     * ############ UI SIMHUB VARIABLES ###############
     * ###############################################
     */
char rpmsValue[13];
char prev_rpmsValue[13];
char rpmRedLineSetting[13];
char gear[2];
char prev_gear[2];
char speed[5];
char currentLapTime[13];
char lastLapTime[13];
char bestLapTime[13];
char sessionBestLiveDeltaSeconds[13];
char sessionBestLiveDeltaProgressSeconds[13];
char tyreWearFrontLeft[6];
char tyreWearFrontRight[6];
char tyreWearRearLeft[6];
char tyreWearRearRight[6];
char tyreTempFrontLeft[6];
char tyreTempFrontRight[6];
char tyreTempRearLeft[6];
char tyreTempRearRight[6];
char brakeBias[5];
char ersPercent[5];
char flagWarning[2];
char frontWingDamage[2];
char rearWingDamage[2];
char tyreDamage[2];
char engBrake[3];
char mgu_h_mode[5];
char mgu_k_delivery[5];
char mgu_k_recovery[5];
char gameRunning[2];

// SCREEN: ui_Idle
void ui_Idle_screen_init(void);
lv_obj_t * ui_Idle;


// SCREEN: ui_Running
void ui_Running_screen_init(void);
lv_obj_t * ui_Running;
lv_obj_t * ui_RunningBarersBar;
lv_obj_t * ui_RunningLabeldrsIndicatorLabel;
lv_obj_t * ui_RunningLabelspeedLabel;
lv_obj_t * ui_RunningLabelspeedValueLabel;
lv_obj_t * ui_RunningLabelgearLabel;
lv_obj_t * ui_RunningLabelgearValueLabel;
lv_obj_t * ui_RunningLabeldeltaTimeLabel;
lv_obj_t * ui_RunningLabeldeltaTimeValueLabel;
lv_obj_t * ui_RunningLabeldiffLabel;
lv_obj_t * ui_RunningLabeldiffValueLabel;
lv_obj_t * ui_RunningLabelbbValueLabel;
lv_obj_t * ui_RunningLabelbbLabel;
lv_obj_t * ui_RunningLabelrpmValueLabel;
lv_obj_t * ui_RunningLabelcurrentLapTimeLabel;
lv_obj_t * ui_RunningLabelcurrentLapTimeValueLabel;
lv_obj_t * ui_RunningLabelbestLapTimeLabel;
lv_obj_t * ui_RunningLabelbestLapTimeValueLabel;
lv_obj_t * ui_RunningLabellastLapTimeLabel;
lv_obj_t * ui_RunningLabellastLapTimeValueLabel;
lv_obj_t * ui_RunningLabel_Ers_ValueLabel;
lv_obj_t * ui_RunningLabeltyreTempLabel;
lv_obj_t * ui_RunningPanelPanel1;
lv_obj_t * ui_RunningLabelmguhModeLabel;
lv_obj_t * ui_RunningLabelmguhModeValueLabel;
lv_obj_t * ui_RunningLabelengineBrakeLabel;
lv_obj_t * ui_RunningLabelengineBrakeLevelValueLabel;
lv_obj_t * ui_RunningLabeltyreWearLabel;
lv_obj_t * ui_RunningPanelPanel2;
lv_obj_t * ui_RunningPanelPanel3;
lv_obj_t * ui_RunningPanelPanel4;
lv_obj_t * ui_RunningPanelPanel5;
lv_obj_t * ui_RunningPanelPanel6;
lv_obj_t * ui_RunningPanelPanel7;
lv_obj_t * ui_RunningPanelPanel8;
lv_obj_t * ui_RunningLabelfrontLeftTyreWearValueLabel;
lv_obj_t * ui_RunningLabelfrontRightTyreWearValueLabel;
lv_obj_t * ui_RunningLabelrearRightTyreWearValueLabel;
lv_obj_t * ui_RunningLabelrearLeftTyreWearValueLabel;
lv_obj_t * ui_RunningLabelleftFrontTyreTempValueLabel;
lv_obj_t * ui_RunningLabelleftRearTyreTempValueLabel2;
lv_obj_t * ui_RunningLabelrightRearTyreTempValueLabel3;
lv_obj_t * ui_RunningLabelrightFrontTyreTempValueLabel1;
lv_obj_t * ui_RunningLabelfrontWingDamageIndicatorLabel;
lv_obj_t * ui_RunningLabelflagIndicatorLabel;
lv_obj_t * ui_RunningLabelrearWingDamageIndicatorLabel;
lv_obj_t * ui_RunningLabelrearWingDamageIndicatorLabel1;
lv_obj_t * ui_RunningLabeltyreDamageIndicatorLabel;
lv_obj_t * ui_RunningLabelmaxRpmIndicatorLabel;
lv_obj_t * ui_RunningLabelmguKRecoveryPercent;
lv_obj_t * ui_RunningLabelmguKRecValueLabel;
lv_obj_t * ui_RunningLabelmguKRecModeLabel;
lv_obj_t * ui_RunningLabelmguKModeValueLabel;



// SCREENL: UPDATE UI LABELS
void updateUI();
int current_screen();
void set_idle_scr();
void set_loading_scr();
void set_running_scr();

// SCREEN: ui_Load
void ui_Load_screen_init(void);
void lv_obj_set_hidden(lv_obj_t *label, int hidden);
lv_obj_t * ui_Load;
void ui_event_LoadImageredBullLogoImage(lv_event_t * e);
lv_obj_t * ui_LoadImageredBullLogoImage;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Startevents___initial_actions0;
const lv_img_dsc_t * ui_imgset_472968869[1] = {&ui_img_680889336};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

int currScr = 0;
int current_screen()
{
    return currScr;
}

void ui_event_LoadImageredBullLogoImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_LoadImageredBullLogoImage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void updateUI() {

    // Speed
    static int prev_speed = 0;
    int spd = atoi(speed);
    if (spd != prev_speed) {
        lv_label_set_text(ui_RunningLabelspeedValueLabel, speed);
        prev_speed = spd;
    }

    // Gear
    if (strcmp(gear, prev_gear) != 0) {
        lv_label_set_text(ui_RunningLabelgearValueLabel, gear);
        strcpy(prev_gear, gear);
    }


    // RPM Percent
    static int prev_rpmsValue = 0;
    int rpm = atoi(rpmsValue);
    if (rpm != prev_rpmsValue) {
        lv_label_set_text(ui_RunningLabelrpmValueLabel, rpmsValue);
        prev_rpmsValue = rpm;
    }

    // Current Lap Time
    static char prev_currentLapTime[16] = "";
    if (strcmp(currentLapTime, prev_currentLapTime) != 0) {
        lv_label_set_text(ui_RunningLabelcurrentLapTimeValueLabel, currentLapTime);
        strcpy(prev_currentLapTime, currentLapTime);
    }

    // Last Lap Time
    static char prev_lastLapTime[16] = "";
    if (strcmp(lastLapTime, prev_lastLapTime) != 0) {
        lv_label_set_text(ui_RunningLabellastLapTimeValueLabel, lastLapTime);
        strcpy(prev_lastLapTime, lastLapTime);
    }


    // Best Lap Time
    static char prev_bestLapTime[16] = "";
    if (strcmp(bestLapTime, prev_bestLapTime) != 0) {
        lv_label_set_text(ui_RunningLabelbestLapTimeValueLabel, bestLapTime);
        strcpy(prev_bestLapTime, bestLapTime);
    }

    // Delta Time
    static char prev_sessionBestLiveDeltaSeconds[16] = "";
    if (strcmp(sessionBestLiveDeltaSeconds, prev_sessionBestLiveDeltaSeconds) != 0) {
        lv_label_set_text(ui_RunningLabeldeltaTimeValueLabel, sessionBestLiveDeltaSeconds);
        strcpy(prev_sessionBestLiveDeltaSeconds, sessionBestLiveDeltaSeconds);
    }

    
    // Brake Bias
    static char prev_brakeBias[16] = "";
    if (strcmp(brakeBias, prev_brakeBias) != 0) {
        lv_label_set_text(ui_RunningLabelbbValueLabel, brakeBias);
        strcpy(prev_brakeBias, brakeBias);
    }

    // ERS
    static int prev_ers_level = 0;
    int ers = atoi(ersPercent);
    if (ers != prev_ers_level)
    {
        lv_label_set_text(ui_RunningLabel_Ers_ValueLabel, ersPercent);
        lv_bar_set_value(ui_RunningBarersBar, (int32_t) ers, LV_ANIM_ON);
        prev_ers_level = ersPercent;
    }

    /*
    -------------> TEMPS
    */

   // Front Left Tyre Temp
    static char prev_tyreTempFrontLeft[16] = "";
    if (strcmp(tyreTempFrontLeft, prev_tyreTempFrontLeft) != 0) {
        lv_label_set_text(ui_RunningLabelleftFrontTyreTempValueLabel, tyreTempFrontLeft);
        strcpy(prev_tyreTempFrontLeft, tyreTempFrontLeft);
    }

    // Front Right Tyre Temp
    static char prev_tyreTempFrontRight[16] = "";
    if (strcmp(tyreTempFrontRight, prev_tyreTempFrontRight) != 0) {
        lv_label_set_text(ui_RunningLabelrightFrontTyreTempValueLabel1, tyreTempFrontRight);
        strcpy(prev_tyreTempFrontRight, tyreTempFrontRight);
    }

    // Rear Left Tyre Temp
    static char prev_tyreTempRearLeft[16] = "";
    if (strcmp(tyreTempRearLeft, prev_tyreTempRearLeft) != 0) {
        lv_label_set_text(ui_RunningLabelleftRearTyreTempValueLabel2, tyreTempRearLeft);
        strcpy(prev_tyreTempRearLeft, tyreTempRearLeft);
    }

    // Rear Right Tyre Temp
    static char prev_tyreTempRearRight[16] = "";
    if (strcmp(tyreTempRearRight, prev_tyreTempRearRight) != 0) {
        lv_label_set_text(ui_RunningLabelrearRightTyreWearValueLabel, tyreTempRearRight);
        strcpy(prev_tyreTempRearRight, tyreTempRearRight);

    }


    /*
    -------------> WEAR
    */

    // Front Left Tyre Wear
    static char prev_tyreWearFrontLeft[16] = "";
    if (strcmp(tyreWearFrontLeft, prev_tyreWearFrontLeft) != 0) {
        lv_label_set_text(ui_RunningLabelfrontLeftTyreWearValueLabel, tyreWearFrontLeft);
        strcpy(prev_tyreWearFrontLeft, tyreWearFrontLeft);
    }

    // Front Right Tyre Wear
    static char prev_tyreWearFrontRight[16] = "";
    if (strcmp(tyreWearFrontRight, prev_tyreWearFrontRight) != 0) {
        lv_label_set_text(ui_RunningLabelfrontRightTyreWearValueLabel, tyreWearFrontRight);
        strcpy(prev_tyreWearFrontRight, tyreWearFrontRight);
    }

    // Rear Left Tyre Wear
    static char prev_tyreWearRearLeft[16] = "";
    if (strcmp(tyreWearRearLeft, prev_tyreWearRearLeft) != 0) {
        lv_label_set_text(ui_RunningLabelrearLeftTyreWearValueLabel, tyreWearRearLeft);
        strcpy(prev_tyreWearRearLeft, tyreWearRearLeft);
    }

    // Rear Right Tyre Wear
    static char prev_tyreWearRearRight[16] = "";
    if (strcmp(tyreWearRearRight, prev_tyreWearRearRight) != 0) {
        lv_label_set_text(ui_RunningLabelrearRightTyreWearValueLabel, tyreWearRearRight);
        strcpy(prev_tyreWearRearRight, tyreWearRearRight);
    }


    // Front Wing Damage Indicator
    static int prev_frontWingDamage = 0;
    int fwDMG = atoi(frontWingDamage);
    if (fwDMG != prev_frontWingDamage) {
        if (fwDMG == 0)
        {
            lv_obj_set_hidden(ui_RunningLabelfrontWingDamageIndicatorLabel, 1);
        }
        else
        {
            lv_obj_set_hidden(ui_RunningLabelfrontWingDamageIndicatorLabel, 0);
                
        }
        prev_frontWingDamage = fwDMG;
    }

    // Rear Wing Damage Indicator
    static int prev_rearWingDamage = 0;
    int rwDmg = atoi(rearWingDamage);
    if (rwDmg != prev_rearWingDamage) {
        if (rwDmg == 0)
        {
            lv_obj_set_hidden(ui_RunningLabelrearWingDamageIndicatorLabel, 1);
        }
        else
        {
            lv_obj_set_hidden(ui_RunningLabelrearWingDamageIndicatorLabel, 0);
                
        }
        prev_rearWingDamage = rwDmg;
    }

    // Tyre Damage Indicator
    static int prev_tyreDamage = 0;
    int tyreDmg = atoi(tyreDamage);
    if (tyreDmg != prev_tyreDamage) {
        if (tyreDmg == 0)
        {
            lv_obj_set_hidden(ui_RunningLabeltyreDamageIndicatorLabel, 1);
        }
        else
        {
            lv_obj_set_hidden(ui_RunningLabelrearWingDamageIndicatorLabel, 0);
                
        }
        prev_tyreDamage = tyreDmg;
    }

    // Engine Brake
    static int prev_engBrake = 0;
    int eb = atoi(engBrake);
    if (eb != prev_engBrake) {
        lv_label_set_text(ui_RunningLabelengineBrakeLevelValueLabel, engBrake);
        prev_engBrake = eb;
    }

    // MGU-H Mode
    static int prev_mgu_h_mode = 0;
    int mguhm = atoi(mgu_h_mode);
    if (mguhm != prev_mgu_h_mode) {
        if (mguhm == 0 )
        {
            lv_label_set_text(ui_RunningLabelmguKModeValueLabel, "Motor");
        } else
        {
            lv_label_set_text(ui_RunningLabelmguKModeValueLabel, "Battery");
        }
        prev_mgu_h_mode = mguhm;
    }

    // MGU-K Recovery Percentage
    static int prev_mguKRec = 0;
    int mguRec = atoi(mgu_k_recovery);
    if (mguRec != prev_mguKRec) {
        mgu_k_recovery[1] = '0';
        mgu_k_recovery[2] = '%';
        lv_label_set_text(ui_RunningLabelmguKRecValueLabel, mgu_k_recovery);
        prev_mguKRec = mguRec;
    }


    // MGU-K Delivery Mode
    static int prev_mgu_k_mode = 0;
    int mgkm = atoi(mgu_k_delivery);
    if (mgkm != prev_mgu_k_mode)
    {
        lv_label_set_text(ui_RunningLabelmguhModeValueLabel, mgu_k_delivery);
        prev_mgu_k_mode = mgkm;
    }


    // Flag Indicator
    static int prev_flagWarning = 0;
    int flagActive = atoi(flagWarning);
    if (flagActive != prev_flagWarning) {
        // change visibility
        if (flagActive == 0)
        {
            lv_obj_set_hidden(ui_RunningLabelflagIndicatorLabel, 1);
        }
        else
        {
            lv_obj_set_hidden(ui_RunningLabelflagIndicatorLabel, 0);
        }

        prev_flagWarning = flagActive;
    }

}

void lv_obj_set_hidden(lv_obj_t *label, int hidden)
{
    _ui_flag_modify(label, LV_OBJ_FLAG_HIDDEN, hidden);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Idle_screen_init();
    ui_Running_screen_init();
    ui_Load_screen_init();
    ui_Screen1_screen_init();
    ui_Startevents___initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Idle);
    currScr = 0;
}

void set_idle_scr()
{
    lv_disp_load_scr(ui_Idle);
    currScr = 0;
}

void set_loading_scr()
{
    lv_disp_load_scr(ui_Load);
    currScr = 1;
}

void set_running_scr()
{
    lv_disp_load_scr(ui_Running);
    currScr = 2;
}