// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#ifndef _DEMO_UI_H
    #define _DEMO_UI_H

    #ifdef __cplusplus
        extern "C" {
    #endif
    
    #include "lvgl.h"

    #include "ui_helpers.h"
    #include "ui_comp.h"
    #include "ui_comp_hook.h"
    #include "ui_events.h"

extern char rpmsValue[13];
extern char prev_rpmsValue[13];
extern char rpmRedLineSetting[13];
extern char gear[2];
extern char prev_gear[2];
extern char speed[5];
extern char currentLapTime[13];
extern char lastLapTime[13];
extern char bestLapTime[13];
extern char sessionBestLiveDeltaSeconds[13];
extern char sessionBestLiveDeltaProgressSeconds[13];
extern char tyreWearFrontLeft[6];
extern char tyreWearFrontRight[6];
extern char tyreWearRearLeft[6];
extern char tyreWearRearRight[6];
extern char tyreTempFrontLeft[6];
extern char tyreTempFrontRight[6];
extern char tyreTempRearLeft[6];
extern char tyreTempRearRight[6];
extern char brakeBias[5];
extern char ersPercent[5];
extern char flagWarning[2];
extern char frontWingDamage[2];
extern char rearWingDamage[2];
extern char tyreDamage[2];
extern char engBrake[3];
extern char mgu_h_mode[5];
extern char mgu_k_delivery[5];
extern char mgu_k_recovery[5];
extern char gameRunning[2];

    // SCREEN: ui_Idle
    void ui_Idle_screen_init(void);
    extern lv_obj_t * ui_Idle;
    // SCREEN: ui_Running
    void ui_Running_screen_init(void);
    extern lv_obj_t * ui_Running;
    extern lv_obj_t * ui_RunningBarersBar;
    extern lv_obj_t * ui_RunningLabeldrsIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelspeedLabel;
    extern lv_obj_t * ui_RunningLabelspeedValueLabel;
    extern lv_obj_t * ui_RunningLabelgearLabel;
    extern lv_obj_t * ui_RunningLabelgearValueLabel;
    extern lv_obj_t * ui_RunningLabeldeltaTimeLabel;
    extern lv_obj_t * ui_RunningLabeldeltaTimeValueLabel;
    extern lv_obj_t * ui_RunningLabeldiffLabel;
    extern lv_obj_t * ui_RunningLabeldiffValueLabel;
    extern lv_obj_t * ui_RunningLabelbbValueLabel;
    extern lv_obj_t * ui_RunningLabelbbLabel;
    extern lv_obj_t * ui_RunningLabelrpmValueLabel;
    extern lv_obj_t * ui_RunningLabelcurrentLapTimeLabel;
    extern lv_obj_t * ui_RunningLabelcurrentLapTimeValueLabel;
    extern lv_obj_t * ui_RunningLabelbestLapTimeLabel;
    extern lv_obj_t * ui_RunningLabelbestLapTimeValueLabel;
    extern lv_obj_t * ui_RunningLabellastLapTimeLabel;
    extern lv_obj_t * ui_RunningLabellastLapTimeValueLabel;
    extern lv_obj_t * ui_RunningLabel_Ers_ValueLabel;
    extern lv_obj_t * ui_RunningLabeltyreTempLabel;
    extern lv_obj_t * ui_RunningPanelPanel1;
    extern lv_obj_t * ui_RunningLabelmguhModeLabel;
    extern lv_obj_t * ui_RunningLabelmguhModeValueLabel;
    extern lv_obj_t * ui_RunningLabelengineBrakeLabel;
    extern lv_obj_t * ui_RunningLabelengineBrakeLevelValueLabel;
    extern lv_obj_t * ui_RunningLabeltyreWearLabel;
    extern lv_obj_t * ui_RunningPanelPanel2;
    extern lv_obj_t * ui_RunningPanelPanel3;
    extern lv_obj_t * ui_RunningPanelPanel4;
    extern lv_obj_t * ui_RunningPanelPanel5;
    extern lv_obj_t * ui_RunningPanelPanel6;
    extern lv_obj_t * ui_RunningPanelPanel7;
    extern lv_obj_t * ui_RunningPanelPanel8;
    extern lv_obj_t * ui_RunningLabelfrontLeftTyreWearValueLabel;
    extern lv_obj_t * ui_RunningLabelfrontRightTyreWearValueLabel;
    extern lv_obj_t * ui_RunningLabelrearRightTyreWearValueLabel;
    extern lv_obj_t * ui_RunningLabelrearLeftTyreWearValueLabel;
    extern lv_obj_t * ui_RunningLabelleftFrontTyreTempValueLabel;
    extern lv_obj_t * ui_RunningLabelleftRearTyreTempValueLabel2;
    extern lv_obj_t * ui_RunningLabelrightRearTyreTempValueLabel3;
    extern lv_obj_t * ui_RunningLabelrightFrontTyreTempValueLabel1;
    extern lv_obj_t * ui_RunningLabelfrontWingDamageIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelflagIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelrearWingDamageIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelrearWingDamageIndicatorLabel1;
    extern lv_obj_t * ui_RunningLabeltyreDamageIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelmaxRpmIndicatorLabel;
    extern lv_obj_t * ui_RunningLabelmguKRecoveryPercent;
    extern lv_obj_t * ui_RunningLabelmguKRecValueLabel;
    extern lv_obj_t * ui_RunningLabelmguKRecModeLabel;
    extern lv_obj_t * ui_RunningLabelmguKModeValueLabel;
    
    // UI UPDATE
    void updateUI();

    // SCREEN: ui_Load
    void ui_Load_screen_init(void);
    extern lv_obj_t * ui_Load;
    void ui_event_LoadImageredBullLogoImage(lv_event_t * e);
    extern lv_obj_t * ui_LoadImageredBullLogoImage;
    // SCREEN: ui_Screen1
    void ui_Screen1_screen_init(void);
    extern lv_obj_t * ui_Screen1;
    extern lv_obj_t * ui_Startevents___initial_actions0;


    LV_IMG_DECLARE(ui_img_akemi_smile_png);    // assets/akemi smile.png
    LV_IMG_DECLARE(ui_img_680889336);    // assets/Screenshot 2024-08-23 121350.png


    int current_screen();



    void ui_init(void);
    void set_idle_scr();
    void set_loading_scr();
    void set_running_scr();

    #ifdef __cplusplus
        } /*extern "C"*/
    #endif


#endif