// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#ifndef _UI_COMP_DASHIMAGE_H
#define _UI_COMP_DASHIMAGE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dashImage
#define UI_COMP_IMAGEDASHIMAGE_IMAGEDASHIMAGE 0
#define _UI_COMP_IMAGEDASHIMAGE_NUM 1
lv_obj_t * ui_ImagedashImage_create(lv_obj_t * comp_parent);
void ui_event_comp_ImagedashImage_ImagedashImage(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
