// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#include "ui.h"

void ui_Idle_screen_init(void)
{
    ui_Idle = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Idle, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Idle, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Idle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Idle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Idle, &ui_img_akemi_smile_png, LV_PART_MAIN | LV_STATE_DEFAULT);


}
