// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#include "ui.h"

void ui_Load_screen_init(void)
{
    ui_Load = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Load, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Load, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Load, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadImageredBullLogoImage = lv_img_create(ui_Load);
    lv_img_set_src(ui_LoadImageredBullLogoImage, &ui_img_680889336);
    lv_obj_set_width(ui_LoadImageredBullLogoImage, 800);
    lv_obj_set_height(ui_LoadImageredBullLogoImage, 487);
    lv_obj_set_align(ui_LoadImageredBullLogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoadImageredBullLogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoadImageredBullLogoImage, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LoadImageredBullLogoImage, 200);

    lv_obj_add_event_cb(ui_LoadImageredBullLogoImage, ui_event_LoadImageredBullLogoImage, LV_EVENT_ALL, NULL);

}
