// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: DEMO

#include "ui.h"

void ui_Running_screen_init(void)
{
    ui_Running = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Running, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Running, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Running, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningBarersBar = lv_bar_create(ui_Running);
    lv_bar_set_value(ui_RunningBarersBar, 85, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RunningBarersBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RunningBarersBar, 286);
    lv_obj_set_height(ui_RunningBarersBar, 24);
    lv_obj_set_x(ui_RunningBarersBar, 20);
    lv_obj_set_y(ui_RunningBarersBar, 435);
    lv_obj_set_align(ui_RunningBarersBar, LV_ALIGN_TOP_MID);
    lv_obj_set_style_radius(ui_RunningBarersBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RunningBarersBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningBarersBar, lv_color_hex(0xC5EC54), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningBarersBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RunningLabeldrsIndicatorLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeldrsIndicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeldrsIndicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeldrsIndicatorLabel, -347);
    lv_obj_set_y(ui_RunningLabeldrsIndicatorLabel, -206);
    lv_obj_set_align(ui_RunningLabeldrsIndicatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabeldrsIndicatorLabel, "DRS");
    lv_obj_add_flag(ui_RunningLabeldrsIndicatorLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabeldrsIndicatorLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabeldrsIndicatorLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabeldrsIndicatorLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeldrsIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeldrsIndicatorLabel, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabeldrsIndicatorLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabeldrsIndicatorLabel, lv_color_hex(0x79F86F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabeldrsIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelspeedLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelspeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelspeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelspeedLabel, 18);
    lv_obj_set_y(ui_RunningLabelspeedLabel, 50);
    lv_label_set_text(ui_RunningLabelspeedLabel, "SP(Kph)");
    lv_obj_set_style_text_color(ui_RunningLabelspeedLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelspeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelspeedLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelspeedValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelspeedValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelspeedValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelspeedValueLabel, 43);
    lv_obj_set_y(ui_RunningLabelspeedValueLabel, 93);
    lv_label_set_text(ui_RunningLabelspeedValueLabel, "200");
    lv_obj_set_style_text_color(ui_RunningLabelspeedValueLabel, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelspeedValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelspeedValueLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelgearLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelgearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelgearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelgearLabel, 5);
    lv_obj_set_y(ui_RunningLabelgearLabel, -223);
    lv_obj_set_align(ui_RunningLabelgearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelgearLabel, "GEAR");
    lv_obj_set_style_text_color(ui_RunningLabelgearLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelgearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelgearLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelgearValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelgearValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelgearValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelgearValueLabel, 387);
    lv_obj_set_y(ui_RunningLabelgearValueLabel, 41);
    lv_label_set_text(ui_RunningLabelgearValueLabel, "5");
    lv_obj_set_style_text_color(ui_RunningLabelgearValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelgearValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelgearValueLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeldeltaTimeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeldeltaTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeldeltaTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeldeltaTimeLabel, 248);
    lv_obj_set_y(ui_RunningLabeldeltaTimeLabel, -151);
    lv_obj_set_align(ui_RunningLabeldeltaTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabeldeltaTimeLabel, "DLT");
    lv_obj_set_style_text_color(ui_RunningLabeldeltaTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeldeltaTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeldeltaTimeLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeldeltaTimeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeldeltaTimeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeldeltaTimeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeldeltaTimeValueLabel, -20);
    lv_obj_set_y(ui_RunningLabeldeltaTimeValueLabel, -120);
    lv_obj_set_align(ui_RunningLabeldeltaTimeValueLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RunningLabeldeltaTimeValueLabel, "-1.311");
    lv_obj_set_style_text_color(ui_RunningLabeldeltaTimeValueLabel, lv_color_hex(0x99F4B8),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeldeltaTimeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeldeltaTimeValueLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeldiffLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeldiffLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeldiffLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeldiffLabel, 252);
    lv_obj_set_y(ui_RunningLabeldiffLabel, -59);
    lv_obj_set_align(ui_RunningLabeldiffLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabeldiffLabel, "DIFF");
    lv_obj_set_style_text_color(ui_RunningLabeldiffLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeldiffLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeldiffLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeldiffValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeldiffValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeldiffValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeldiffValueLabel, 347);
    lv_obj_set_y(ui_RunningLabeldiffValueLabel, -36);
    lv_obj_set_align(ui_RunningLabeldiffValueLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningLabeldiffValueLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningLabeldiffValueLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_RunningLabeldiffValueLabel, "55");
    lv_obj_set_style_text_color(ui_RunningLabeldiffValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeldiffValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeldiffValueLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelbbValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelbbValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelbbValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelbbValueLabel, 335);
    lv_obj_set_y(ui_RunningLabelbbValueLabel, 33);
    lv_obj_set_align(ui_RunningLabelbbValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelbbValueLabel, "55.%");
    lv_obj_set_style_text_color(ui_RunningLabelbbValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelbbValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelbbValueLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelbbLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelbbLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelbbLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelbbLabel, 245);
    lv_obj_set_y(ui_RunningLabelbbLabel, 0);
    lv_obj_set_align(ui_RunningLabelbbLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelbbLabel, "BB");
    lv_obj_set_style_text_color(ui_RunningLabelbbLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelbbLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelbbLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrpmValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrpmValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrpmValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrpmValueLabel, 5);
    lv_obj_set_y(ui_RunningLabelrpmValueLabel, 209);
    lv_obj_set_align(ui_RunningLabelrpmValueLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_RunningLabelrpmValueLabel, "10657.RPM");
    lv_obj_set_style_text_color(ui_RunningLabelrpmValueLabel, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrpmValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrpmValueLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelcurrentLapTimeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelcurrentLapTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelcurrentLapTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelcurrentLapTimeLabel, -339);
    lv_obj_set_y(ui_RunningLabelcurrentLapTimeLabel, -76);
    lv_obj_set_align(ui_RunningLabelcurrentLapTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelcurrentLapTimeLabel, "CURR");
    lv_obj_set_style_text_color(ui_RunningLabelcurrentLapTimeLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelcurrentLapTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelcurrentLapTimeLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelcurrentLapTimeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelcurrentLapTimeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelcurrentLapTimeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelcurrentLapTimeValueLabel, 37);
    lv_obj_set_y(ui_RunningLabelcurrentLapTimeValueLabel, 192);
    lv_label_set_text(ui_RunningLabelcurrentLapTimeValueLabel, "1:21.433");
    lv_obj_set_style_text_color(ui_RunningLabelcurrentLapTimeValueLabel, lv_color_hex(0x99F4B8),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelcurrentLapTimeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelcurrentLapTimeValueLabel, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelbestLapTimeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelbestLapTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelbestLapTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelbestLapTimeLabel, 9);
    lv_obj_set_y(ui_RunningLabelbestLapTimeLabel, 37);
    lv_obj_set_align(ui_RunningLabelbestLapTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelbestLapTimeLabel, "BEST");
    lv_obj_set_style_text_color(ui_RunningLabelbestLapTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelbestLapTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelbestLapTimeLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelbestLapTimeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelbestLapTimeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelbestLapTimeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelbestLapTimeValueLabel, 335);
    lv_obj_set_y(ui_RunningLabelbestLapTimeValueLabel, 297);
    lv_label_set_text(ui_RunningLabelbestLapTimeValueLabel, "1:20.122");
    lv_obj_set_style_text_color(ui_RunningLabelbestLapTimeValueLabel, lv_color_hex(0xFAFAFA),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelbestLapTimeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelbestLapTimeValueLabel, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabellastLapTimeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabellastLapTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabellastLapTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabellastLapTimeLabel, -338);
    lv_obj_set_y(ui_RunningLabellastLapTimeLabel, 27);
    lv_obj_set_align(ui_RunningLabellastLapTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabellastLapTimeLabel, "LAST");
    lv_obj_set_style_text_color(ui_RunningLabellastLapTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabellastLapTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabellastLapTimeLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabellastLapTimeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabellastLapTimeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabellastLapTimeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabellastLapTimeValueLabel, 30);
    lv_obj_set_y(ui_RunningLabellastLapTimeValueLabel, 293);
    lv_label_set_text(ui_RunningLabellastLapTimeValueLabel, "1:21.433 (-1.331)");
    lv_obj_set_style_text_color(ui_RunningLabellastLapTimeValueLabel, lv_color_hex(0x99F4B8),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabellastLapTimeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabellastLapTimeValueLabel, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabel_Ers_ValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabel_Ers_ValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabel_Ers_ValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabel_Ers_ValueLabel, 374);
    lv_obj_set_y(ui_RunningLabel_Ers_ValueLabel, 159);
    lv_obj_set_align(ui_RunningLabel_Ers_ValueLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RunningLabel_Ers_ValueLabel, "80%");
    lv_obj_set_style_text_color(ui_RunningLabel_Ers_ValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabel_Ers_ValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabel_Ers_ValueLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeltyreTempLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeltyreTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeltyreTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeltyreTempLabel, -322);
    lv_obj_set_y(ui_RunningLabeltyreTempLabel, 119);
    lv_obj_set_align(ui_RunningLabeltyreTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabeltyreTempLabel, "TEMP:");
    lv_obj_set_style_text_color(ui_RunningLabeltyreTempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeltyreTempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeltyreTempLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguhModeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguhModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguhModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguhModeLabel, 119);
    lv_obj_set_y(ui_RunningLabelmguhModeLabel, -222);
    lv_obj_set_align(ui_RunningLabelmguhModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelmguhModeLabel, "MGU-H");
    lv_obj_set_style_text_color(ui_RunningLabelmguhModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguhModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguhModeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguhModeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguhModeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguhModeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguhModeValueLabel, 488);
    lv_obj_set_y(ui_RunningLabelmguhModeValueLabel, 31);
    lv_label_set_text(ui_RunningLabelmguhModeValueLabel, "HOTLAP");
    lv_obj_set_style_text_color(ui_RunningLabelmguhModeValueLabel, lv_color_hex(0xC3F362), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguhModeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguhModeValueLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelengineBrakeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelengineBrakeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelengineBrakeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelengineBrakeLabel, -231);
    lv_obj_set_y(ui_RunningLabelengineBrakeLabel, -222);
    lv_obj_set_align(ui_RunningLabelengineBrakeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelengineBrakeLabel, "ENG_BRK");
    lv_obj_set_style_text_color(ui_RunningLabelengineBrakeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelengineBrakeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelengineBrakeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelengineBrakeLevelValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelengineBrakeLevelValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelengineBrakeLevelValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelengineBrakeLevelValueLabel, 154);
    lv_obj_set_y(ui_RunningLabelengineBrakeLevelValueLabel, 31);
    lv_label_set_text(ui_RunningLabelengineBrakeLevelValueLabel, "5/13");
    lv_obj_set_style_text_color(ui_RunningLabelengineBrakeLevelValueLabel, lv_color_hex(0xE1FF4A),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelengineBrakeLevelValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelengineBrakeLevelValueLabel, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabeltyreWearLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabeltyreWearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabeltyreWearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabeltyreWearLabel, 336);
    lv_obj_set_y(ui_RunningLabeltyreWearLabel, 115);
    lv_obj_set_align(ui_RunningLabeltyreWearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabeltyreWearLabel, "WEAR:");
    lv_obj_set_style_text_color(ui_RunningLabeltyreWearLabel, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabeltyreWearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabeltyreWearLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelfrontLeftTyreWearValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelfrontLeftTyreWearValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelfrontLeftTyreWearValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelfrontLeftTyreWearValueLabel, 240);
    lv_obj_set_y(ui_RunningLabelfrontLeftTyreWearValueLabel, 156);
    lv_obj_set_align(ui_RunningLabelfrontLeftTyreWearValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelfrontLeftTyreWearValueLabel, "17");
    lv_obj_set_style_text_color(ui_RunningLabelfrontLeftTyreWearValueLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelfrontLeftTyreWearValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelfrontLeftTyreWearValueLabel, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelfrontRightTyreWearValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelfrontRightTyreWearValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelfrontRightTyreWearValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelfrontRightTyreWearValueLabel, 333);
    lv_obj_set_y(ui_RunningLabelfrontRightTyreWearValueLabel, 156);
    lv_obj_set_align(ui_RunningLabelfrontRightTyreWearValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelfrontRightTyreWearValueLabel, "17");
    lv_obj_set_style_text_color(ui_RunningLabelfrontRightTyreWearValueLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelfrontRightTyreWearValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelfrontRightTyreWearValueLabel, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrearRightTyreWearValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrearRightTyreWearValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrearRightTyreWearValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrearRightTyreWearValueLabel, 332);
    lv_obj_set_y(ui_RunningLabelrearRightTyreWearValueLabel, 199);
    lv_obj_set_align(ui_RunningLabelrearRightTyreWearValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrearRightTyreWearValueLabel, "17");
    lv_obj_set_style_text_color(ui_RunningLabelrearRightTyreWearValueLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrearRightTyreWearValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrearRightTyreWearValueLabel, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrearLeftTyreWearValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrearLeftTyreWearValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrearLeftTyreWearValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrearLeftTyreWearValueLabel, 240);
    lv_obj_set_y(ui_RunningLabelrearLeftTyreWearValueLabel, 200);
    lv_obj_set_align(ui_RunningLabelrearLeftTyreWearValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrearLeftTyreWearValueLabel, "17");
    lv_obj_set_style_text_color(ui_RunningLabelrearLeftTyreWearValueLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrearLeftTyreWearValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrearLeftTyreWearValueLabel, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelleftFrontTyreTempValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelleftFrontTyreTempValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelleftFrontTyreTempValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelleftFrontTyreTempValueLabel, -361);
    lv_obj_set_y(ui_RunningLabelleftFrontTyreTempValueLabel, 158);
    lv_obj_set_align(ui_RunningLabelleftFrontTyreTempValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelleftFrontTyreTempValueLabel, "90");
    lv_obj_set_style_text_color(ui_RunningLabelleftFrontTyreTempValueLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelleftFrontTyreTempValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelleftFrontTyreTempValueLabel, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelleftRearTyreTempValueLabel2 = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelleftRearTyreTempValueLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelleftRearTyreTempValueLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelleftRearTyreTempValueLabel2, -361);
    lv_obj_set_y(ui_RunningLabelleftRearTyreTempValueLabel2, 196);
    lv_obj_set_align(ui_RunningLabelleftRearTyreTempValueLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelleftRearTyreTempValueLabel2, "90");
    lv_obj_set_style_text_color(ui_RunningLabelleftRearTyreTempValueLabel2, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelleftRearTyreTempValueLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelleftRearTyreTempValueLabel2, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrightRearTyreTempValueLabel3 = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrightRearTyreTempValueLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrightRearTyreTempValueLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrightRearTyreTempValueLabel3, -256);
    lv_obj_set_y(ui_RunningLabelrightRearTyreTempValueLabel3, 196);
    lv_obj_set_align(ui_RunningLabelrightRearTyreTempValueLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrightRearTyreTempValueLabel3, "90");
    lv_obj_set_style_text_color(ui_RunningLabelrightRearTyreTempValueLabel3, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrightRearTyreTempValueLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrightRearTyreTempValueLabel3, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrightFrontTyreTempValueLabel1 = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrightFrontTyreTempValueLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrightFrontTyreTempValueLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrightFrontTyreTempValueLabel1, -255);
    lv_obj_set_y(ui_RunningLabelrightFrontTyreTempValueLabel1, 156);
    lv_obj_set_align(ui_RunningLabelrightFrontTyreTempValueLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrightFrontTyreTempValueLabel1, "90");
    lv_obj_add_flag(ui_RunningLabelrightFrontTyreTempValueLabel1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelrightFrontTyreTempValueLabel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelrightFrontTyreTempValueLabel1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrightFrontTyreTempValueLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrightFrontTyreTempValueLabel1, &lv_font_montserrat_30,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelfrontWingDamageIndicatorLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelfrontWingDamageIndicatorLabel, 150);
    lv_obj_set_y(ui_RunningLabelfrontWingDamageIndicatorLabel, 73);
    lv_obj_set_align(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelfrontWingDamageIndicatorLabel, "FW\nDMG");
    lv_obj_add_flag(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabelfrontWingDamageIndicatorLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelfrontWingDamageIndicatorLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelfrontWingDamageIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RunningLabelfrontWingDamageIndicatorLabel, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelfrontWingDamageIndicatorLabel, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabelfrontWingDamageIndicatorLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabelfrontWingDamageIndicatorLabel, lv_color_hex(0xED3636),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabelfrontWingDamageIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelflagIndicatorLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelflagIndicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelflagIndicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelflagIndicatorLabel, 154);
    lv_obj_set_y(ui_RunningLabelflagIndicatorLabel, -152);
    lv_obj_set_align(ui_RunningLabelflagIndicatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelflagIndicatorLabel, "FLG\nWRN");
    lv_obj_add_flag(ui_RunningLabelflagIndicatorLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabelflagIndicatorLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelflagIndicatorLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelflagIndicatorLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelflagIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RunningLabelflagIndicatorLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelflagIndicatorLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabelflagIndicatorLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabelflagIndicatorLabel, lv_color_hex(0xEDFE7F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabelflagIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrearWingDamageIndicatorLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrearWingDamageIndicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrearWingDamageIndicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrearWingDamageIndicatorLabel, -140);
    lv_obj_set_y(ui_RunningLabelrearWingDamageIndicatorLabel, -129);
    lv_obj_set_align(ui_RunningLabelrearWingDamageIndicatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrearWingDamageIndicatorLabel, "RW\nDMG");
    lv_obj_add_flag(ui_RunningLabelrearWingDamageIndicatorLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabelrearWingDamageIndicatorLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelrearWingDamageIndicatorLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelrearWingDamageIndicatorLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrearWingDamageIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RunningLabelrearWingDamageIndicatorLabel, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrearWingDamageIndicatorLabel, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabelrearWingDamageIndicatorLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabelrearWingDamageIndicatorLabel, lv_color_hex(0xED3636),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabelrearWingDamageIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelrearWingDamageIndicatorLabel1 = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelrearWingDamageIndicatorLabel1, 150);
    lv_obj_set_y(ui_RunningLabelrearWingDamageIndicatorLabel1, -38);
    lv_obj_set_align(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelrearWingDamageIndicatorLabel1, "RW\nDMG");
    lv_obj_add_flag(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabelrearWingDamageIndicatorLabel1,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelrearWingDamageIndicatorLabel1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelrearWingDamageIndicatorLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RunningLabelrearWingDamageIndicatorLabel1, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelrearWingDamageIndicatorLabel1, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabelrearWingDamageIndicatorLabel1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabelrearWingDamageIndicatorLabel1, lv_color_hex(0xED3636),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabelrearWingDamageIndicatorLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmaxRpmIndicatorLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmaxRpmIndicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmaxRpmIndicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmaxRpmIndicatorLabel, 353);
    lv_obj_set_y(ui_RunningLabelmaxRpmIndicatorLabel, 4);
    lv_label_set_text(ui_RunningLabelmaxRpmIndicatorLabel, "MAX");
    lv_obj_add_flag(ui_RunningLabelmaxRpmIndicatorLabel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_RunningLabelmaxRpmIndicatorLabel,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_RunningLabelmaxRpmIndicatorLabel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_RunningLabelmaxRpmIndicatorLabel, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmaxRpmIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmaxRpmIndicatorLabel, &lv_font_montserrat_46,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RunningLabelmaxRpmIndicatorLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RunningLabelmaxRpmIndicatorLabel, lv_color_hex(0xC70606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RunningLabelmaxRpmIndicatorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguKRecoveryPercent = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguKRecoveryPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguKRecoveryPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguKRecoveryPercent, -123);
    lv_obj_set_y(ui_RunningLabelmguKRecoveryPercent, -222);
    lv_obj_set_align(ui_RunningLabelmguKRecoveryPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelmguKRecoveryPercent, "MGU-K_REC%");
    lv_obj_set_style_text_color(ui_RunningLabelmguKRecoveryPercent, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguKRecoveryPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguKRecoveryPercent, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguKRecValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguKRecValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguKRecValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguKRecValueLabel, 267);
    lv_obj_set_y(ui_RunningLabelmguKRecValueLabel, 29);
    lv_label_set_text(ui_RunningLabelmguKRecValueLabel, "30");
    lv_obj_set_style_text_color(ui_RunningLabelmguKRecValueLabel, lv_color_hex(0xE1FF4A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguKRecValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguKRecValueLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguKRecModeLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguKRecModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguKRecModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguKRecModeLabel, 260);
    lv_obj_set_y(ui_RunningLabelmguKRecModeLabel, -222);
    lv_obj_set_align(ui_RunningLabelmguKRecModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningLabelmguKRecModeLabel, "MGU-K-REC");
    lv_obj_set_style_text_color(ui_RunningLabelmguKRecModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguKRecModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguKRecModeLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningLabelmguKModeValueLabel = lv_label_create(ui_Running);
    lv_obj_set_width(ui_RunningLabelmguKModeValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningLabelmguKModeValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RunningLabelmguKModeValueLabel, 645);
    lv_obj_set_y(ui_RunningLabelmguKModeValueLabel, 31);
    lv_label_set_text(ui_RunningLabelmguKModeValueLabel, "BAT");
    lv_obj_set_style_text_color(ui_RunningLabelmguKModeValueLabel, lv_color_hex(0xC3F362), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RunningLabelmguKModeValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RunningLabelmguKModeValueLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
